#!/usr/bin/env bash
# Runtime: networking stack. NetworkManager, systemd-resolved, firewall,
# Mullvad daemon on daily, DNS resolution works.
source "${BASH_SOURCE%/*}/../lib/common.sh"

profile=$(detect_profile)

describe "NetworkManager"
assert_service_active NetworkManager.service
# Firewall service (when enabled by NixOS firewall, not nftables standalone)
assert_service_active firewall.service
describe "systemd-resolved"
assert_service_active systemd-resolved.service

describe "DNS resolution still works"
# Don't use external name lookups; systemd-resolved replies over its dbus
# interface. `resolvectl query` is the idiomatic check.
if command -v resolvectl >/dev/null 2>&1; then
  if resolvectl query nixos.org >/dev/null 2>&1; then
    pass "resolvectl query nixos.org succeeds"
  else
    warn "resolvectl query nixos.org failed (possibly offline)"
  fi
fi
if getent hosts nixos.org >/dev/null 2>&1; then
  pass "getent hosts nixos.org succeeds"
else
  warn "getent hosts nixos.org failed (possibly offline)"
fi

describe "Mullvad app mode state"
if [[ "$profile" == "daily" ]]; then
  assert_service_active mullvad-daemon.service
  if command -v mullvad >/dev/null 2>&1; then
    pass "mullvad CLI in PATH"
    st=$(mullvad status --json 2>/dev/null || mullvad status 2>/dev/null || true)
    if [[ -n "$st" ]]; then
      info "mullvad status: $(printf '%s' "$st" | head -c 200)"
    fi
  else
    warn "mullvad CLI not in PATH"
  fi
else
  # paranoid must not run the app-mode daemon (self-owned WG is staged off).
  if systemctl cat mullvad-daemon.service >/dev/null 2>&1; then
    assert_service_inactive mullvad-daemon.service
  else
    pass "mullvad-daemon.service absent on paranoid"
  fi
fi

describe "self-owned WireGuard is not active (staged off)"
# Interface should NOT exist.
if ip link show wg-mullvad >/dev/null 2>&1; then
  fail "wg-mullvad interface exists despite staged-off policy"
else
  pass "wg-mullvad interface absent (expected)"
fi
# No wireguard-wg-mullvad.service running.
if systemctl is-active --quiet wireguard-wg-mullvad.service 2>/dev/null; then
  fail "wireguard-wg-mullvad.service is active despite staged-off policy"
else
  pass "wireguard-wg-mullvad.service inactive"
fi

describe "NetworkManager DNS backend"
if [[ "$profile" == "daily" ]]; then
  nm_dns=$(/run/current-system/sw/bin/nmcli general | awk -F: 'NR==2{print $NF}' 2>/dev/null || true)
  if command -v NetworkManager >/dev/null 2>&1; then
    # Check /etc/NetworkManager/conf.d for dns=systemd-resolved
    if grep -Rq 'dns=systemd-resolved' /etc/NetworkManager/ 2>/dev/null; then
      pass "daily: NetworkManager uses systemd-resolved for DNS"
    else
      warn "NetworkManager dns= line not found under /etc/NetworkManager/conf.d"
    fi
  fi
fi

describe "daily-only: wake-on-lan policy on enp5s0"
if [[ "$profile" == "daily" ]]; then
  if ip link show enp5s0 >/dev/null 2>&1; then
    # /etc/systemd/network/40-enp5s0.link is generated by networking.interfaces
    if [[ -e /etc/systemd/network/40-enp5s0.link ]] \
       && grep -q 'WakeOnLan' /etc/systemd/network/40-enp5s0.link 2>/dev/null; then
      pass "WoL link file present for enp5s0"
    else
      warn "enp5s0 WoL link file absent; WakeOnLan may not apply"
    fi
  else
    skip "enp5s0 not present on this host"
  fi
fi

describe "basic firewall state"
if command -v nft >/dev/null 2>&1; then
  if [[ "$(id -u)" -eq 0 ]]; then
    ruleset=$(nft list ruleset 2>/dev/null)
    if [[ -n "$ruleset" ]]; then
      pass "nft ruleset non-empty"
    else
      warn "nft ruleset empty — firewall may be off"
    fi
  else
    info "nft ruleset inspection requires root"
  fi
else
  info "nft not in PATH"
fi

describe "firewall: daily udp/7 (WoL magic) allowed"
if [[ "$profile" == "daily" ]] && sudo -n true 2>/dev/null; then
  if sudo -n iptables -S 2>/dev/null | grep -q 'dport 7' \
     || sudo -n nft list chain inet nixos-fw input 2>/dev/null | grep -q 'udp dport 7'; then
    pass "UDP/7 allow rule present"
  else
    warn "UDP/7 allow rule not found in firewall (magic WoL traffic may be blocked)"
  fi
fi
